### ISSUE TITLE
Can not open character sheet on Foundry 10

### ISSUE THREAD

**Issue by tbsvttr** [corndog-foundry/blackvoid#6]
When I open the character sheet on Foundry 10 nothing happen and on the console I get this error:

```
Foundry VTT | Rendering BlackVoidActorSheet
       TypeError: An error occurred while rendering BlackVoidActorSheet 28. Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at BlackVoidActorSheet.getData (actor-sheet.js:24:29)
    at BlackVoidActorSheet._render (foundry.js:4959:29)
    at BlackVoidActorSheet._render (foundry.js:5684:17)
    at BlackVoidActorSheet.render (foundry.js:4918:10)
    at BlackVoidActorSheet.render (foundry.js:6254:18)
    at ActorDirectory._onClickDocumentName (foundry.js:59946:16)
    at HTMLOListElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

I guess the API changed and you reference something that was an object and is now not there anymore.

**Comment by conormcc98** [comment]
I have no time nor interest in returning to this project. Feel free to fork it and fix it yourself if you wish to.

**Comment by tbsvttr** [comment]
@corndog-foundry In that case I would like to ask you to archive this project. So that this state is visible to others.
